#!/bin/bash

ssh aur-dev setup-repo ${1}
git submodule add aur-dev:/${1}.git
cp gitignore "${1}/.gitignore"
for hook in *.hook; do
    ln -sf "$(pwd)/${hook}" ".git/modules/${1}/hooks/${hook%.hook}"
done
